version: '3'
services:
        mysql:
                image: mysql/mysql-server
                volumes:
                       - /var/lib/mysql:/var/lib/mysql
                container_name: mysql
                working_dir: /mysql
        service:
                build:
                        dockerfile: Dockerfile_service
                        context: $HOME/Documents/Project2/
                container_name: service
                depends_on:
                        - mysql
                ports:
                        - "8080:8080"
