version: '3'
services:
        mysql:
                image: mysql/mysql-server
                volumes:
                       - /var/lib/mysql:/var/lib/mysql
                container_name: mysql
                working_dir: /mysql
                networks: 
                        - backend
        service:
                build:
                        dockerfile: Dockerfile_service
                        context: $HOME/Documents/Project2/
                container_name: service
                depends_on:
                        - mysql
                networks: 
                        - backend
                        - frontend
                ports: 
                        - 8181:8080

networks: 
        frontend:

        backend:

