version: '3'
services:
        mysql:
                image: mysql/mysql-server
                volumes:
                       - /var/lib/mysql:/var/lib/mysql  
                container_name: mysql
        service:
                build:
                        dockerfile: Dockerfile_service
                        context: /project2/Server/
                depends_on:
                        - mysql
                ports:
                        - "8080:8080"